version: '2.1'

services:
  css-with-react:
    image: css-with-react
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 6633:6633
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 scripts/start.js